name: state-roads-vehicle-inspection

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    expose:
      - 5000
    restart: unless-stopped
    env_file: ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    expose:
      - 3000
    restart: unless-stopped
    env_file: ./client/.env
